"""Add added_by and image_url to product table

Revision ID: e4b1477e4972
Revises: 43f85a675d66
Create Date: 2025-06-13 08:02:34.878081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4b1477e4972'
down_revision: Union[str, None] = '43f85a675d66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('added_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'products', 'users', ['added_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'added_by')
    op.drop_column('products', 'image_url')
    # ### end Alembic commands ###
